(function () {
  const fixStyles=document.createElement('link');fixStyles.rel='stylesheet';fixStyles.href='styles-fixes.css';document.head.appendChild(fixStyles);
  const frame=document.querySelector('#showcase-frame'),link=document.querySelector('#full-link'),list=document.querySelector('#showcase-list'),projects=window.PORTFOLIO_PROJECTS||[],activityGallery=window.ACTIVITY_GALLERY||[],showcases=window.SHOWCASE_ITEMS||[],ui=window.PORTFOLIO_UI||{viewProject:'View project',activityPreview:'activity preview',screen:'screen',expandImage:'Expand image',closeImage:'Close enlarged image',imageDialog:'Enlarged image'}; let lastTrigger=null,imageTrigger=null;
  function selectShowcase(id){const item=showcases.find(x=>x.id===id)||showcases[0];if(!item||!frame||!link)return;frame.src=item.src;link.href=item.src;document.querySelectorAll('.showcase-choice').forEach((b,i)=>{b.id=`showcase-tab-${showcases[i].id}`;const on=b.dataset.id===item.id;b.setAttribute('aria-selected',on);b.tabIndex=on?0:-1});const panel=document.querySelector('#showcase-panel');if(panel)panel.setAttribute('aria-labelledby',`showcase-tab-${item.id}`)}
  function restartShowcase(){if(frame)frame.src=frame.src}
  function enhanceExpandableImages(root=document){root.querySelectorAll('.project-media img,.activity-card img,.dialog-gallery img,.rise-card>img').forEach(img=>{img.classList.add('expandable-image');img.tabIndex=0;img.setAttribute('role','button');img.setAttribute('aria-label',`${ui.expandImage}: ${img.alt}`)})}
  function openImagePreview(image,trigger=image){const dialog=document.querySelector('#image-lightbox'),preview=document.querySelector('#lightbox-image'),caption=document.querySelector('#lightbox-caption');if(!dialog||!preview||!image)return;imageTrigger=trigger;preview.src=image.currentSrc||image.src;preview.alt=image.alt;caption.textContent=image.alt;dialog.showModal();dialog.querySelector('.lightbox-close')?.focus()}
  function closeImagePreview(){const dialog=document.querySelector('#image-lightbox');if(dialog?.open)dialog.close();imageTrigger?.focus?.();imageTrigger=null}
  function renderProjects(filter='all'){const t=document.querySelector('#project-list');t.innerHTML=projects.filter(p=>filter==='all'||p.type===filter).map(p=>`<article class="project-row"><div class="project-media"><img class="project-shot" src="${p.image}" alt="${p.imageAlt}" loading="lazy"></div><div><h3>${p.title}</h3><p>${p.summary}</p></div><div class="project-meta"><span class="project-type">${p.type}</span><span class="project-year">${p.year}</span></div><button class="project-open" data-project="${p.id}">${ui.viewProject} ↗</button></article>`).join('');t.querySelectorAll('.project-open').forEach(b=>b.addEventListener('click',()=>openProject(b.dataset.project,b)));enhanceExpandableImages(t)}
  function renderActivityGallery(){const t=document.querySelector('#activity-gallery');if(!t)return;t.innerHTML=activityGallery.map(item=>`<article class="activity-card"><img src="${item.image}" alt="${item.title}: ${ui.activityPreview}" loading="lazy"><div><span>${item.type}</span><h4>${item.title}</h4></div></article>`).join('');enhanceExpandableImages(t)}
  function openProject(id,trigger){const p=projects.find(x=>x.id===id),dialog=document.querySelector('#project-dialog');if(!p||!dialog)return;lastTrigger=trigger||document.activeElement;document.querySelector('#dialog-title').textContent=p.title;document.querySelector('#dialog-copy').textContent=p.detail;document.querySelector('#dialog-gallery').innerHTML=p.gallery.map((src,i)=>`<img src="${src}" alt="${p.title}: ${ui.screen} ${i+1}">`).join('');enhanceExpandableImages(dialog);dialog.showModal()}
  function closeProject(){const dialog=document.querySelector('#project-dialog');if(dialog)dialog.close();if(lastTrigger)lastTrigger.focus()}
  if(list&&frame&&link){showcases.forEach((item,i)=>{const b=document.createElement('button');b.className='showcase-choice';b.dataset.id=item.id;b.id=`showcase-tab-${item.id}`;b.tabIndex=i===0?0:-1;b.setAttribute('role','tab');b.setAttribute('aria-controls','showcase-panel');b.setAttribute('aria-selected',i===0);b.innerHTML=`<small>${item.eyebrow}</small>${item.title}`;b.addEventListener('click',()=>selectShowcase(item.id));b.addEventListener('keydown',e=>{const bs=[...list.querySelectorAll('[role=tab]')],i=bs.indexOf(b);let n=i;if(e.key==='ArrowRight')n=(i+1)%bs.length;if(e.key==='ArrowLeft')n=(i-1+bs.length)%bs.length;if(e.key==='Home')n=0;if(e.key==='End')n=bs.length-1;if(n!==i){e.preventDefault();bs[n].focus();selectShowcase(bs[n].dataset.id)}});list.appendChild(b)});frame.parentElement.id='showcase-panel';frame.parentElement.setAttribute('role','tabpanel');frame.parentElement.setAttribute('aria-labelledby','showcase-tab-evidence');frame.addEventListener('error',()=>frame.parentElement.classList.add('has-error'));frame.addEventListener('load',()=>frame.parentElement.classList.remove('has-error'));const restart=document.querySelector('#restart');if(restart)restart.addEventListener('click',restartShowcase)}
  const dialogClose=document.querySelector('.dialog-close'),dialog=document.querySelector('#project-dialog');if(dialogClose)dialogClose.addEventListener('click',closeProject);if(dialog)dialog.addEventListener('click',e=>{if(e.target===e.currentTarget)closeProject()});
  const imageDialog=document.querySelector('#image-lightbox'),lightboxClose=document.querySelector('.lightbox-close');if(lightboxClose){lightboxClose.setAttribute('aria-label',ui.closeImage);lightboxClose.addEventListener('click',closeImagePreview)}if(imageDialog){imageDialog.setAttribute('aria-label',ui.imageDialog);imageDialog.addEventListener('click',e=>{if(e.target===e.currentTarget)closeImagePreview()});imageDialog.addEventListener('keydown',e=>{if(e.key==='Escape'){e.preventDefault();closeImagePreview()}})}document.addEventListener('click',e=>{const img=e.target.closest?.('.expandable-image');if(img)openImagePreview(img)});document.addEventListener('keydown',e=>{const img=e.target.closest?.('.expandable-image');if(img&&(e.key==='Enter'||e.key===' ')){e.preventDefault();openImagePreview(img)}});
  document.querySelectorAll('.filter').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('.filter').forEach(x=>{x.classList.remove('is-active');x.setAttribute('aria-pressed',x===b?'true':'false')});b.classList.add('is-active');renderProjects(b.dataset.filter)}));
  const mobile=document.querySelector('#mobile-nav');if(mobile)mobile.addEventListener('click',()=>{const open=mobile.getAttribute('aria-expanded')==='true';mobile.setAttribute('aria-expanded',!open);const nav=document.querySelector('header nav');if(nav){nav.classList.toggle('is-open',!open);nav.style.display=open?'none':'flex'}});
  document.querySelectorAll('section').forEach(s=>s.classList.add('reveal'));if('IntersectionObserver'in window&&!window.matchMedia('(prefers-reduced-motion: reduce)').matches){const o=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add('is-visible');o.unobserve(e.target)}}),{threshold:.12});document.querySelectorAll('.reveal').forEach(s=>o.observe(s))}else document.querySelectorAll('.reveal').forEach(s=>s.classList.add('is-visible'));if(document.querySelector('#project-list'))renderProjects();renderActivityGallery();enhanceExpandableImages();window.selectShowcase=selectShowcase;window.restartShowcase=restartShowcase;window.renderProjects=renderProjects;window.openProject=openProject;window.closeProject=closeProject;window.openImagePreview=openImagePreview;window.closeImagePreview=closeImagePreview;
})();
