(function () {
  const projects = [
    { id: 'verification', title: 'Estudio de verificación', type: 'Práctica interactiva', year: '2026', image: 'assets/activity-previews/verification-studio.png', imageAlt: 'Vista previa del estudio de verificación', summary: 'Una experiencia guiada que ayuda a comparar señales y tomar una decisión con seguridad.', detail: 'Una práctica de varios pasos con contenido progresivo, exploración guiada, decisiones, retroalimentación y avance condicionado.', gallery: ['assets/activity-previews/verification-studio.png', 'assets/activity-previews/comparison.png'] },
    { id: 'interface', title: 'Recorrido guiado de interfaz', type: 'Simulación de sistema', year: '2026', image: 'assets/activity-previews/interface-walkthrough.png', imageAlt: 'Vista previa del recorrido guiado de interfaz', summary: 'Un entorno realista para practicar el uso de software con zonas interactivas y guía paso a paso.', detail: 'Una simulación segura para compartir que muestra navegación estructurada, zonas interactivas, estados visitados y una secuencia clara.', gallery: ['assets/activity-previews/interface-walkthrough.png', 'assets/activity-previews/guided-scenario.png'] },
    { id: 'branching', title: 'Escenario de decisiones ramificadas', type: 'Aprendizaje basado en escenarios', year: '2026', image: 'assets/activity-previews/branching-decision.png', imageAlt: 'Vista previa del escenario de decisiones ramificadas', summary: 'Un escenario donde cada decisión conduce a retroalimentación relacionada con el contexto.', detail: 'Un formato diseñado con decisiones realistas, opciones equilibradas, retroalimentación correctiva y oportunidades para volver a intentar.', gallery: ['assets/activity-previews/branching-decision.png', 'assets/activity-previews/escalation-reveal.png'] },
    { id: 'roleplay', title: 'Presentación completa de juego de roles', type: 'Aprendizaje basado en escenarios', year: '2026', image: 'assets/activity-previews/role-play.png', imageAlt: 'Vista previa de una conversación de juego de roles', summary: 'Una práctica de conversación con diálogo, acompañamiento y reflexión.', detail: 'Una estructura completa que combina diálogo por etapas, orientación, reflexión y avance controlado.', gallery: ['assets/activity-previews/role-play.png', 'assets/activity-previews/guided-scenario.png'] },
    { id: 'sorting', title: 'Evaluación de clasificación', type: 'Práctica interactiva', year: '2026', image: 'assets/activity-previews/sorting-check.png', imageAlt: 'Vista previa de la evaluación de clasificación', summary: 'Una actividad práctica de clasificación con retroalimentación inmediata y explicativa.', detail: 'Un formato reutilizable con categorías claras, controles accesibles por teclado, reintentos y señal de finalización.', gallery: ['assets/activity-previews/sorting-check.png', 'assets/activity-previews/single-choice-check.png'] },
    { id: 'matching', title: 'Actividad de asociación', type: 'Práctica interactiva', year: '2026', image: 'assets/activity-previews/matching-activity.png', imageAlt: 'Vista previa de la actividad de asociación', summary: 'Una interacción visual que conecta acciones, motivos y resultados.', detail: 'Una actividad flexible para trabajar pasos de procesos, conceptos, terminología y razonamiento para la toma de decisiones.', gallery: ['assets/activity-previews/matching-activity.png', 'assets/activity-previews/comparison.png'] }
  ];
  window.PORTFOLIO_PROJECTS = projects;
  window.ACTIVITY_GALLERY = [
    { title: 'Presentación guiada de escenario', type: 'Recorrido acompañado', image: 'assets/activity-previews/guided-scenario.png' },
    { title: 'Comparación de dos categorías', type: 'Apoyo para decisiones', image: 'assets/activity-previews/comparison.png' },
    { title: 'Revelación progresiva de escalamiento', type: 'Contenido condicionado', image: 'assets/activity-previews/escalation-reveal.png' },
    { title: 'Evaluación de selección única', type: 'Evaluación', image: 'assets/activity-previews/single-choice-check.png' }
  ];
  window.SHOWCASE_ITEMS = [
    { id: 'evidence', title: 'Desafío de revisión de evidencia', eyebrow: '01 / Práctica de revisión', src: 'showcase/es/evidence-review/index.html', note: 'Revisa un conjunto de registros ficticios y toma una decisión final.' },
    { id: 'simulation', title: 'Simulación guiada de sistema', eyebrow: '02 / Práctica de sistema', src: 'showcase/es/system-simulation/index.html', note: 'Practica un proceso ficticio con revisión, reintentos y estados de finalización.' }
  ];
  window.PORTFOLIO_UI = { viewProject: 'Ver proyecto', activityPreview: 'vista previa de la actividad', screen: 'pantalla', expandImage: 'Ampliar imagen', closeImage: 'Cerrar imagen ampliada', imageDialog: 'Imagen ampliada' };
})();
